### ISSUE TITLE
Player.goTo only checks for NoteOn events on channel 1

### ISSUE THREAD

**Issue by sk-io** [5tan/cxxmidi#1]
This sends loads of instantaneous note on/offs if notes are present on other channels
The issue seems to be at line 224 in abstract.hpp

**Comment by 5tan** [comment]
Hello @sk-io 

Playing a MIDI file from a certain timpepoint is a little bit complex, because MIDI protocol is "stateful".

By stateful I mean that sending a message to the output will have a result depending on current state of the synth and player. 

**Example 1**
If we send a "note off" message, either a sound will stop (because there was a corresponding "note on" message before) or nothing will happen (because there was no prior "note on" message).

**Example 2**
If we send a "note on" message it might sound like a trumpet or like a piano (depending on what program change message was sent before).

In order to play a song from a certain timepoint, we have to set a synthesizer state in this timepoint. 

Here is how `goTo` function (rewinding) works:
1) Output is being reset (L210). Now we have a clean synthesizer state.
2) Player state is being reset (L209 + L211-2013)
3) All events except "note on" are being executed (L215-L231).

Why step 3 is required? Because we need to set synthesizer and player state. E.g. set channel effects, pitch bends, song tempo, etc. 

Why "note on" events are being omitted? Because we want `goTo` function to be quiet (make no sounds).

To answer your doubts:
> This sends loads of instantaneous note on/offs if notes are present on other channels
> The issue seems to be at line 224 in abstract.hpp

Yes, loads of instantaneous messages are being sent. This is intentional, to set synthesizer state.
"Note on" messages are not being sent.

I see no bug here.

PS 
This function could be optimized. Instead of sending all messages, we could resolve synth state at a given time point, and send only required messages. This is difficult.

**Comment by sk-io** [comment]
Sorry I worded the issue so confusingly, I understand what goTo is doing.
What I meant was:

`if( event[0] != Message::NoteOn)`
The second nibble of the event status byte (event[0]) is the MIDI channel, all of the Message enums are set hex codes corresponding to events on channel 1.

Instead you might only compare the first nibble:
`if( (event[0] & 0xF0) != Message::NoteOn)`

**Comment by sk-io** [comment]
In fact from a quick glance it seems like only channel 1 is acknowledged throughout the library?

**Comment by 5tan** [comment]
thank you! I will try to fix it soon.

**Comment by 5tan** [comment]
Fixed on development branch: https://github.com/5tan/cxxmidi/commit/1f0ed1aa0b46066b3cdf8ddbba00f58f47e151c6

> In fact from a quick glance it seems like only channel 1 is acknowledged throughout the library?

It looks like I haven't made the same mistake in other places:
https://github.com/5tan/cxxmidi/blob/master/include/cxxmidi/file.hpp#L420
https://github.com/5tan/cxxmidi/blob/master/examples/qtmidieditor/trackmodel.cpp#L157
https://github.com/5tan/cxxmidi/blob/master/include/cxxmidi/message.hpp#L219
